#!/bin/sh

rrdtool create cart.rrd \
	--start N --step 1 \
	DS:speed:GAUGE:300:0:140 \
	DS:cpu_temp:GAUGE:300:0:140 \
	DS:case_temp:GAUGE:300:0:140 \
	DS:outside_temp:GAUGE:300:0:140 \
	DS:current:GAUGE:300:0:10000 \
	DS:voltage:GAUGE:300:0:15 \
        RRA:AVERAGE:0.5:1:345600 \
        RRA:AVERAGE:0.5:60:57600 \
        RRA:AVERAGE:0.5:1800:175200

# every 1 sec for 4 days
# every 1 min for 40 days
# every 30 minutes for 10 years
# http://rrdtools.appspot.com/
